name: CI
on: [workflow_dispatch, pull_request, push]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install client
        run: cd client && npm install && npm run build
      - uses: fastai/workflows/nbdev-ci@master
