name: CI
on: [workflow_dispatch, pull_request, push]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: settings.ini

      - name: Install Dependencies
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          pip install -Uq nbdev
          nbdev_install_quarto
          test -f setup.py && pip install -e ".[dev]"
          cd client && npm install && npm run build

      - name: Run Tests
        shell: bash
        run: |
          nbdev_test
